version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  librarian:
    parameters:
      python_version:
        type: string
    docker:
      - image: continuumio/miniconda:latest
    environment:
      PYTHON: << parameters.python_version >>
      ENV_NAME: librarian_tests
      LIBRARIAN_CONFIG_PATH: ./server/server-config-ci.json
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ .Branch }}-{{ checksum "ci/librarian_tests.yml" }}
      - run:
          name: configure conda environment
          command: ./ci/install-circle.sh
      - run:
          name: launch librarian server
          command: |
            conda activate ${ENV_NAME}
            cd server
            ./runserver.py &
      - run:
          name: run librarian tests
          command: |
            conda activate ${ENV_NAME}
            mkdir test-reports
            pytest --with-xunit --xunit-file=test-reports/xunit.xml --cover-xml
      - save_cache:
          key: deps-{{ .Branch }}-{{ checksum "ci/librarian_tests.yml" }}
          paths:
            - "/opt/conda/envs/${ENV_NAME}/"
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports
      - codecov/upload:
          file: ./coverage.xml

workflows:
  version: 2
  build_and_test:
    jobs:
      - librarian:
          name: librarian_2.7
          python_version: 2.7
