version: 2.1
orbs:
  codecov: codecov/codecov@1.0.4
jobs:
  librarian:
    parameters:
      python_version:
        type: string
    docker:
      - image: continuumio/miniconda:latest
      - image: circleci/postgres:11
        environment:
          POSTGRES_USER: librarian
          POSTGRES_DB: librarian_test
    environment:
      PYTHON: << parameters.python_version >>
      ENV_NAME: librarian_tests
      LIBRARIAN_CONFIG_PATH: ${CIRCLE_WORKING_DIRECTORY}/ci/server-config-ci.json
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ .Branch }}-{{ checksum "ci/librarian_tests.yml" }}
      - run:
          name: configure conda environment
          command: ./ci/install-circle.sh
      - run:
          name: install hera_librarian package in base python environment
          command: |
            pip install numpy scipy astropy
            pip install pyuvdata aipy
            python setup.py install
      - run:
          name: set up librarian database
          command: |
            source ~/.bashrc
            conda activate ${ENV_NAME}
            cd server
            alembic upgrade head
            cd ..
      - run:
          name: run librarian tests
          command: |
            source ~/.bashrc
            conda activate ${ENV_NAME}
            pytest --cov=hera_librarian --cov=librarian_server --cov-report=xml --cov-report=term
      - save_cache:
          key: deps-{{ .Branch }}-{{ checksum "ci/librarian_tests.yml" }}
          paths:
            - "/opt/conda/envs/${ENV_NAME}/"
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports
      - codecov/upload:
          file: ./coverage.xml

workflows:
  version: 2
  build_and_test:
    jobs:
      - librarian:
          name: librarian_2.7
          python_version: "2.7"
